import type { Folder, LinkItem } from "./types";

export const folders: Folder[] = [
  { id: "dev", name: "개발", count: 4 },
  { id: "design", name: "디자인", count: 3 },
  { id: "article", name: "읽을거리", count: 3 },
  { id: "shopping", name: "쇼핑", count: 2 },
];

export const links: LinkItem[] = [
  {
    id: "1",
    title: "Next.js Documentation",
    url: "https://nextjs.org/docs",
    description: "App Router와 최신 기능을 정리한 Next.js 공식 문서.",
    folderId: "dev",
    createdAt: "2026-07-20",
  },
  {
    id: "2",
    title: "Tailwind CSS",
    url: "https://tailwindcss.com",
    description: "유틸리티 클래스 기반으로 빠르게 UI를 만드는 CSS 프레임워크.",
    folderId: "dev",
    createdAt: "2026-07-19",
  },
  {
    id: "3",
    title: "TypeScript Handbook",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    description: "타입스크립트 문법과 활용법을 정리한 공식 핸드북.",
    folderId: "dev",
    createdAt: "2026-07-18",
  },
  {
    id: "4",
    title: "MDN Web Docs",
    url: "https://developer.mozilla.org",
    description: "웹 표준 기술에 대한 가장 신뢰할 수 있는 레퍼런스.",
    folderId: "dev",
    createdAt: "2026-07-15",
  },
  {
    id: "5",
    title: "Dribbble",
    url: "https://dribbble.com",
    description: "전 세계 디자이너들의 포트폴리오와 영감을 모아둔 커뮤니티.",
    folderId: "design",
    createdAt: "2026-07-14",
  },
  {
    id: "6",
    title: "Figma",
    url: "https://figma.com",
    description: "협업 기반의 UI/UX 디자인 및 프로토타이핑 툴.",
    folderId: "design",
    createdAt: "2026-07-12",
  },
  {
    id: "7",
    title: "Coolors",
    url: "https://coolors.co",
    description: "빠르게 컬러 팔레트를 생성하고 테스트할 수 있는 도구.",
    folderId: "design",
    createdAt: "2026-07-10",
  },
  {
    id: "8",
    title: "The Pragmatic Engineer",
    url: "https://newsletter.pragmaticengineer.com",
    description: "소프트웨어 업계 동향을 다루는 뉴스레터.",
    folderId: "article",
    createdAt: "2026-07-08",
  },
  {
    id: "9",
    title: "Overreacted",
    url: "https://overreacted.io",
    description: "Dan Abramov의 개인 블로그, React와 프론트엔드에 대한 깊이 있는 글.",
    folderId: "article",
    createdAt: "2026-07-05",
  },
  {
    id: "10",
    title: "Hacker News",
    url: "https://news.ycombinator.com",
    description: "개발자와 스타트업 관련 소식을 모아보는 커뮤니티 뉴스 사이트.",
    folderId: "article",
    createdAt: "2026-07-02",
  },
  {
    id: "11",
    title: "무신사",
    url: "https://www.musinsa.com",
    description: "온라인 패션 편집숍, 다양한 브랜드의 의류를 판매.",
    folderId: "shopping",
    createdAt: "2026-06-28",
  },
  {
    id: "12",
    title: "쿠팡",
    url: "https://www.coupang.com",
    description: "로켓배송으로 유명한 국내 이커머스 플랫폼.",
    folderId: "shopping",
    createdAt: "2026-06-25",
  },
];
